version: '2'

services:

  zammad:
    image: tamtsin/zammad-docker-compose:zammad
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    restart: on-failure
    volumes:
      - data-zammad:/home/zammad

  zammad-nginx:
    depends_on:
      - zammad
    image: tamtsin/zammad-docker-compose:zammad-nginx
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-railsserver
      - zammad-websocket
    ports:
      - "8080:80"
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-railsserver:
    depends_on:
      - zammad
    image: tamtsin/zammad-docker-compose:zammad-railsserver
    environment:
      - DATABASE_HOST=zammad-postgresql
      - DATABASE_NAME=zammad_production
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    labels:
      io.rancher.container.pull_image: always
    depends_on:
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-scheduler:
    depends_on:
      - zammad
    image: tamtsin/zammad-docker-compose:zammad-scheduler
    environment:
      - DATABASE_HOST=zammad-postgresql
      - DATABASE_NAME=zammad_production
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-websocket:
    depends_on:
      - zammad
    image: tamtsin/zammad-docker-compose:zammad-websocket
    environment:
      - DATABASE_HOST=zammad-postgresql
      - DATABASE_NAME=zammad_production
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad

volumes:
  data-zammad:
    driver: local
