version: '2'

services:

  zammad:
    scale: 1
    start_on_create: true

  zammad-nginx:
    scale: 1
    start_on_create: true

  zammad-scheduler:
    scale: 1
    start_on_create: true

  zammad-railsserver:
    scale: 1
    start_on_create: true

  zammad-websocket:
    scale: 1
    start_on_create: true
